#!/bin/sh

MAKE=gmake

D=$(pwd)
cd "$D/apps-gorm" || exit 1
"${MAKE}" debug=yes
sudo -E "${MAKE}" GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install

cd "$D/apps-gworkspace" || exit 1
./configure
"${MAKE}" debug=yes
sudo -E "${MAKE}" GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install

cd "$D/apps-projectcenter" || exit 1
"${MAKE}" debug=yes
sudo -E "${MAKE}" GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install

cd "$D/apps-systempreferences" || exit 1
"${MAKE}" debug=yes
sudo -E "${MAKE}" GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install

cd "$D/apps-thematic" || exit 1
"${MAKE}" debug=yes
sudo -E "${MAKE}" GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install



